### PR TITLE
Suggestion/slsa v1 scheme update

### PR DESCRIPTION
**Pull request by houdini91**
I am still getting to understand spector vision and imp. (first time looking at rust).

This PR is just a DRAFT to display the differences i think may be nice on the prov scheme as i am building one of my own and it will be awesome if it was synced with the specture one..
i know its a generated file but i require some learning curve to understand how to effect specture rust to generate and validate using this scheme..

@mlieberman85 Hope its ok i am using the repo, feel free to delete the PR if its not relevant.

### CODE REVIEW

**Comment by mlieberman85** [comment]
This is useful! Yeah, so I will take a look at the macro I'm using. I think the macro annotation can take in a "description." Let me check how that works.

**Comment by houdini91** [comment]
@mlieberman85 i added some changed to the provenance.rs (take a good look because i am new  to rust).
* Added discriptions for some fields.
* Removed internalParameters, resolvedDependencies from required list.
* Renamed Metadata struct to BuildMetadata


I could not for the life of me get the external_parameters and internal_parameters to be defined as a object format.
They simply are generated as "true" which i don't understand if this is basically a free json?

**Comment by houdini91** [comment]
I changed the 
* Changed `external_parameters`,`internal_parameters` and annotation to **Param to serde_json::Map<String, serde_json::Value>**.

The json schema looks better but for some reason when i try testing against the new genrated schema it fails.

external_parameters: json!({"key": "value"}) <-- seem like a issue..

```
   --> src/models/intoto/provenance.rs:130:37
    |
130 |                 external_parameters:serde_json::Map<String, serde_json::Value>!({"key": "value"}),
    |                                     ^^^^^^^^^^^^^^^^^^^^^^ expected `Map<String, Value>`, found `bool`
    |
    = note: expected struct `serde_json::Map<std::string::String, serde_json::Value>`
                 found type `bool`

error[E0308]: mismatched types
   --> src/models/intoto/provenance.rs:131:38
    |
131 |                 internal_parameters: json!({"key": "value"}),
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<Map<String, Value>>`, found `Value`
    |
````

**Comment by mlieberman85** [comment]
So for the second error it will be

```
json!({"key": "value"}).as_object().unwrap().clone()
```

the `json!` macro defaults to a Value, so it needs to be converted.

**Comment by mlieberman85** [comment]
Also it looks like some of these values that are set as optional are in fact requires like: `invocation_id`

**Comment by mlieberman85** [comment]
oops, I was misreading the build id for the invocation id. I'll do another look over, but I think I fixed the issues.

**Comment by mlieberman85** [comment]
I'm going to merge this in and then I have a few other fixes I'll add in right after.

**Pull request merged**
